### PR TITLE
Add missing license

### PR DESCRIPTION
**Pull request by btrd**
Source

> Comme toutes les productions associées au projet STOPCOVID, elle sera mise en open source, sous licence MPL.

https://www.inria.fr/fr/contact-tracing-bruno-sportisse-pdg-dinria-donne-quelques-elements-pour-mieux-comprendre-les-enjeux

Related https://github.com/ROBERT-proximity-tracing/documents/issues/5

### CODE REVIEW

**Comment by MattiSG** [comment]
Fixes #5.

**Review by MattiSG — APPROVED** [review]
Fixes #5.

**Comment by peg500and** [comment]
Quand ?

**Comment by MattiSG** [comment]
The chosen license in #5 was CC-BY-NC-SA.

Superseded by 99fa0623feaab5368aca79f3ec15ec7dd5a89cd6.

**Comment by bzg** [comment]
MPL (or Open License 2.0) would have been a better choice than CC-BY-NC-SA, I think (as I commented [here](https://github.com/ROBERT-proximity-tracing/documents/issues/5#issuecomment-620879119).)

**Pull request closed without merging**
